# FIXME: Oops, in the next version I should put CLOCK_27MHZ on a proper clock-capable pin.
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLOCK_27MHZ]

# ---------------- Clock ----------------
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVCMOS33} [get_ports CLOCK_27MHZ]

# ---------------- HDMI ----------------

set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {HDMI_CTL1}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {HDMI_CTL2}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports {HDMI_CTL3}]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[0]}]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[1]}]
set_property -dict {PACKAGE_PIN J10 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[2]}]
set_property -dict {PACKAGE_PIN K10 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[3]}]
set_property -dict {PACKAGE_PIN G9 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[4]}]
set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[5]}]
set_property -dict {PACKAGE_PIN K9 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[6]}]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[7]}]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[8]}]
set_property -dict {PACKAGE_PIN D13 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[9]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[10]}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[11]}]
set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[12]}]
set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[13]}]
set_property -dict {PACKAGE_PIN G10 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[14]}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[15]}]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[16]}]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[17]}]
set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[18]}]
set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[19]}]
set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[20]}]
set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[21]}]
set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[22]}]
set_property -dict {PACKAGE_PIN F9 IOSTANDARD LVCMOS33} [get_ports {HDMI_DATA[23]}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports HDMI_BSEL]
set_property -dict {PACKAGE_PIN J9  IOSTANDARD LVCMOS33} [get_ports HDMI_CLK]
set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVCMOS33} [get_ports HDMI_DE]
set_property -dict {PACKAGE_PIN J12 IOSTANDARD LVCMOS33} [get_ports HDMI_DKEN]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports HDMI_DSEL]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33} [get_ports HDMI_EDGE]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS33} [get_ports HDMI_HSYNC]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33} [get_ports HDMI_ISEL]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports HDMI_MSEN]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports HDMI_PD]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports HDMI_VSYNC]

# ---------------- NV ----------------
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD LVCMOS33} [get_ports NV_CLK]
set_property -dict {PACKAGE_PIN AF14 IOSTANDARD LVCMOS33} [get_ports NV_CS]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVCMOS33} [get_ports {NV_D[0]}]
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVCMOS33} [get_ports {NV_D[1]}]
set_property -dict {PACKAGE_PIN AE15 IOSTANDARD LVCMOS33} [get_ports {NV_D[2]}]
set_property -dict {PACKAGE_PIN AD15 IOSTANDARD LVCMOS33} [get_ports {NV_D[3]}]

# ---------------- WIFI ----------------
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVCMOS33} [get_ports WIFI_CLK]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports WIFI_CSn]
set_property -dict {PACKAGE_PIN Y15 IOSTANDARD LVCMOS33} [get_ports WIFI_D0_MOSI]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVCMOS33} [get_ports WIFI_D1_MISO]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports WIFI_D2]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports WIFI_D3]
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD LVCMOS33} [get_ports WIFI_READY]

# ---------------- Parallel ports P0 / P1 / P2 ----------------
set_property -dict {PACKAGE_PIN AD13 IOSTANDARD LVCMOS33} [get_ports {P0_DATA[0]}]
set_property -dict {PACKAGE_PIN AC13 IOSTANDARD LVCMOS33} [get_ports {P0_DATA[1]}]
set_property -dict {PACKAGE_PIN AD14 IOSTANDARD LVCMOS33} [get_ports {P0_DATA[2]}]
set_property -dict {PACKAGE_PIN AC14 IOSTANDARD LVCMOS33} [get_ports {P0_DATA[3]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports {P1_DATA[0]}]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {P1_DATA[1]}]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports {P1_DATA[2]}]
set_property -dict {PACKAGE_PIN AA13 IOSTANDARD LVCMOS33} [get_ports {P1_DATA[3]}]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {P2_DATA[0]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {P2_DATA[1]}]
set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVCMOS33} [get_ports {P2_DATA[2]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {P2_DATA[3]}]

# ---------------- RP2040 comms ----------------
#set_property -dict {PACKAGE_PIN G12 IOSTANDARD LVCMOS33} [get_ports {RP2040_COMMS[0]}]
#set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {RP2040_COMMS[1]}]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS33} [get_ports {RP2040_UARTRX}]
#set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {RP2040_COMMS[3]}]

# ---------------- FTDI UART ----------------
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports UART_RXD]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports UART_TXD]

# ---------------- LEDs ----------------
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports {leds[0]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {leds[1]}]




set_property -dict {PACKAGE_PIN C18 IOSTANDARD DIFF_SSTL12_DCI} [get_ports C0_SYS_CLK_0_clk_p]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD DIFF_SSTL12_DCI} [get_ports C0_SYS_CLK_0_clk_n]

set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pins_dqs_c[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pins_dqs_c[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pins_dqs_t[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddr4_pins_dqs_t[1]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_pins_ck_c[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddr4_pins_ck_t[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports ddr4_pins_reset_n]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dm_n[0]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dm_n[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[0]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[10]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[11]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[12]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[13]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[14]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[15]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[8]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddr4_pins_dq[9]}]
set_property IOSTANDARD SSTL12_DCI [get_ports ddr4_pins_act_n]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[10]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[11]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[12]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[13]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[14]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[15]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[16]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[2]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[3]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[4]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[5]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[6]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[7]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[8]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_adr[9]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_ba[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_ba[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_bg[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_cke[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_cs_n[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddr4_pins_odt[0]}]
set_property SLEW FAST [get_ports ddr4_pins_act_n]
set_property SLEW FAST [get_ports {ddr4_pins_adr[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[10]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[11]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[12]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[13]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[14]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[15]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[16]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[1]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[2]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[3]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[4]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[5]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[6]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[7]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[8]}]
set_property SLEW FAST [get_ports {ddr4_pins_adr[9]}]
set_property SLEW FAST [get_ports {ddr4_pins_ba[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_ba[1]}]
set_property SLEW FAST [get_ports {ddr4_pins_bg[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_ck_c[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_ck_t[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_cke[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_cs_n[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_dm_n[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_dm_n[1]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[10]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[11]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[12]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[13]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[14]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[15]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[1]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[2]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[3]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[4]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[5]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[6]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[7]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[8]}]
set_property SLEW FAST [get_ports {ddr4_pins_dq[9]}]
set_property SLEW FAST [get_ports {ddr4_pins_dqs_c[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_dqs_c[1]}]
set_property SLEW FAST [get_ports {ddr4_pins_dqs_t[0]}]
set_property SLEW FAST [get_ports {ddr4_pins_dqs_t[1]}]
set_property SLEW FAST [get_ports {ddr4_pins_odt[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports ddr4_pins_act_n]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[13]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[16]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_adr[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_ba[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_ba[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_bg[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_ck_c[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_ck_t[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_cke[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_cs_n[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dm_n[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dm_n[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[13]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dq[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dqs_c[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dqs_c[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dqs_t[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_dqs_t[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddr4_pins_odt[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dm_n[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dm_n[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[10]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[11]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[12]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[13]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[14]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[15]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[7]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[8]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dq[9]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dqs_c[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dqs_c[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dqs_t[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr4_pins_dqs_t[1]}]
set_property PACKAGE_PIN G22 [get_ports ddr4_pins_act_n]
set_property PACKAGE_PIN L20 [get_ports {ddr4_pins_adr[0]}]
set_property PACKAGE_PIN J23 [get_ports {ddr4_pins_adr[10]}]
set_property PACKAGE_PIN M21 [get_ports {ddr4_pins_adr[11]}]
set_property PACKAGE_PIN J21 [get_ports {ddr4_pins_adr[12]}]
set_property PACKAGE_PIN L19 [get_ports {ddr4_pins_adr[13]}]
set_property PACKAGE_PIN J19 [get_ports {ddr4_pins_adr[14]}]
set_property PACKAGE_PIN K22 [get_ports {ddr4_pins_adr[15]}]
set_property PACKAGE_PIN J24 [get_ports {ddr4_pins_adr[16]}]
set_property PACKAGE_PIN L23 [get_ports {ddr4_pins_adr[1]}]
set_property PACKAGE_PIN M19 [get_ports {ddr4_pins_adr[2]}]
set_property PACKAGE_PIN K25 [get_ports {ddr4_pins_adr[3]}]
set_property PACKAGE_PIN K23 [get_ports {ddr4_pins_adr[4]}]
set_property PACKAGE_PIN K20 [get_ports {ddr4_pins_adr[5]}]
set_property PACKAGE_PIN M25 [get_ports {ddr4_pins_adr[6]}]
set_property PACKAGE_PIN M26 [get_ports {ddr4_pins_adr[7]}]
set_property PACKAGE_PIN K18 [get_ports {ddr4_pins_adr[8]}]
set_property PACKAGE_PIN M20 [get_ports {ddr4_pins_adr[9]}]
set_property PACKAGE_PIN M24 [get_ports {ddr4_pins_ba[0]}]
set_property PACKAGE_PIN K26 [get_ports {ddr4_pins_ba[1]}]
set_property PACKAGE_PIN J20 [get_ports {ddr4_pins_bg[0]}]
set_property PACKAGE_PIN L24 [get_ports {ddr4_pins_ck_t[0]}]
set_property PACKAGE_PIN L25 [get_ports {ddr4_pins_ck_c[0]}]
set_property PACKAGE_PIN F22 [get_ports {ddr4_pins_cke[0]}]
set_property PACKAGE_PIN G25 [get_ports {ddr4_pins_cs_n[0]}]
set_property PACKAGE_PIN G24 [get_ports {ddr4_pins_dm_n[0]}]
set_property PACKAGE_PIN E25 [get_ports {ddr4_pins_dm_n[1]}]
set_property PACKAGE_PIN H21 [get_ports {ddr4_pins_dq[0]}]
set_property PACKAGE_PIN D24 [get_ports {ddr4_pins_dq[10]}]
set_property PACKAGE_PIN D25 [get_ports {ddr4_pins_dq[11]}]
set_property PACKAGE_PIN C26 [get_ports {ddr4_pins_dq[12]}]
set_property PACKAGE_PIN D26 [get_ports {ddr4_pins_dq[13]}]
set_property PACKAGE_PIN E23 [get_ports {ddr4_pins_dq[14]}]
set_property PACKAGE_PIN F23 [get_ports {ddr4_pins_dq[15]}]
set_property PACKAGE_PIN G26 [get_ports {ddr4_pins_dq[1]}]
set_property PACKAGE_PIN H23 [get_ports {ddr4_pins_dq[2]}]
set_property PACKAGE_PIN H24 [get_ports {ddr4_pins_dq[3]}]
set_property PACKAGE_PIN H22 [get_ports {ddr4_pins_dq[4]}]
set_property PACKAGE_PIN H26 [get_ports {ddr4_pins_dq[5]}]
set_property PACKAGE_PIN J25 [get_ports {ddr4_pins_dq[6]}]
set_property PACKAGE_PIN J26 [get_ports {ddr4_pins_dq[7]}]
set_property PACKAGE_PIN B25 [get_ports {ddr4_pins_dq[8]}]
set_property PACKAGE_PIN B26 [get_ports {ddr4_pins_dq[9]}]
set_property PACKAGE_PIN F24 [get_ports {ddr4_pins_dqs_t[0]}]
set_property PACKAGE_PIN F25 [get_ports {ddr4_pins_dqs_c[0]}]
set_property PACKAGE_PIN D23 [get_ports {ddr4_pins_dqs_t[1]}]
set_property PACKAGE_PIN C24 [get_ports {ddr4_pins_dqs_c[1]}]
set_property PACKAGE_PIN E26 [get_ports {ddr4_pins_odt[0]}]
set_property PACKAGE_PIN L22 [get_ports ddr4_pins_reset_n]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
