// Generated by CIRCT firtool-1.128.0
module Registers(
  input         clock,
                reset,
  input  [31:0] io_in,
  input  [4:0]  io_select,
  input         io_write_enable,
                io_enable,
  output [31:0] io_out
);

  reg  [31:0]       regs_0;
  reg  [31:0]       regs_1;
  reg  [31:0]       regs_2;
  reg  [31:0]       regs_3;
  reg  [31:0]       regs_4;
  reg  [31:0]       regs_5;
  reg  [31:0]       regs_6;
  reg  [31:0]       regs_7;
  reg  [31:0]       regs_8;
  reg  [31:0]       regs_9;
  reg  [31:0]       regs_10;
  reg  [31:0]       regs_11;
  reg  [31:0]       regs_12;
  reg  [31:0]       regs_13;
  reg  [31:0]       regs_14;
  reg  [31:0]       regs_15;
  reg  [31:0]       regs_16;
  reg  [31:0]       regs_17;
  reg  [31:0]       regs_18;
  reg  [31:0]       regs_19;
  reg  [31:0]       regs_20;
  reg  [31:0]       regs_21;
  reg  [31:0]       regs_22;
  reg  [31:0]       regs_23;
  reg  [31:0]       regs_24;
  reg  [31:0]       regs_25;
  reg  [31:0]       regs_26;
  reg  [31:0]       regs_27;
  reg  [31:0]       regs_28;
  reg  [31:0]       regs_29;
  reg  [31:0]       regs_30;
  reg  [31:0]       regs_31;
  wire [31:0][31:0] _GEN =
    {{regs_31},
     {regs_30},
     {regs_29},
     {regs_28},
     {regs_27},
     {regs_26},
     {regs_25},
     {regs_24},
     {regs_23},
     {regs_22},
     {regs_21},
     {regs_20},
     {regs_19},
     {regs_18},
     {regs_17},
     {regs_16},
     {regs_15},
     {regs_14},
     {regs_13},
     {regs_12},
     {regs_11},
     {regs_10},
     {regs_9},
     {regs_8},
     {regs_7},
     {regs_6},
     {regs_5},
     {regs_4},
     {regs_3},
     {regs_2},
     {regs_1},
     {regs_0}};
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 32'h0;
      regs_1 <= 32'h0;
      regs_2 <= 32'h0;
      regs_3 <= 32'h0;
      regs_4 <= 32'h0;
      regs_5 <= 32'h0;
      regs_6 <= 32'h0;
      regs_7 <= 32'h0;
      regs_8 <= 32'h0;
      regs_9 <= 32'h0;
      regs_10 <= 32'h0;
      regs_11 <= 32'h0;
      regs_12 <= 32'h0;
      regs_13 <= 32'h0;
      regs_14 <= 32'h0;
      regs_15 <= 32'h0;
      regs_16 <= 32'h0;
      regs_17 <= 32'h0;
      regs_18 <= 32'h0;
      regs_19 <= 32'h0;
      regs_20 <= 32'h0;
      regs_21 <= 32'h0;
      regs_22 <= 32'h0;
      regs_23 <= 32'h0;
      regs_24 <= 32'h0;
      regs_25 <= 32'h0;
      regs_26 <= 32'h0;
      regs_27 <= 32'h0;
      regs_28 <= 32'h0;
      regs_29 <= 32'h0;
      regs_30 <= 32'h0;
      regs_31 <= 32'h0;
    end
    else begin
      automatic logic _GEN_0 = io_enable & io_write_enable & (|io_select);
      if (_GEN_0 & ~(|io_select))
        regs_0 <= io_in;
      if (_GEN_0 & io_select == 5'h1)
        regs_1 <= io_in;
      if (_GEN_0 & io_select == 5'h2)
        regs_2 <= io_in;
      if (_GEN_0 & io_select == 5'h3)
        regs_3 <= io_in;
      if (_GEN_0 & io_select == 5'h4)
        regs_4 <= io_in;
      if (_GEN_0 & io_select == 5'h5)
        regs_5 <= io_in;
      if (_GEN_0 & io_select == 5'h6)
        regs_6 <= io_in;
      if (_GEN_0 & io_select == 5'h7)
        regs_7 <= io_in;
      if (_GEN_0 & io_select == 5'h8)
        regs_8 <= io_in;
      if (_GEN_0 & io_select == 5'h9)
        regs_9 <= io_in;
      if (_GEN_0 & io_select == 5'hA)
        regs_10 <= io_in;
      if (_GEN_0 & io_select == 5'hB)
        regs_11 <= io_in;
      if (_GEN_0 & io_select == 5'hC)
        regs_12 <= io_in;
      if (_GEN_0 & io_select == 5'hD)
        regs_13 <= io_in;
      if (_GEN_0 & io_select == 5'hE)
        regs_14 <= io_in;
      if (_GEN_0 & io_select == 5'hF)
        regs_15 <= io_in;
      if (_GEN_0 & io_select == 5'h10)
        regs_16 <= io_in;
      if (_GEN_0 & io_select == 5'h11)
        regs_17 <= io_in;
      if (_GEN_0 & io_select == 5'h12)
        regs_18 <= io_in;
      if (_GEN_0 & io_select == 5'h13)
        regs_19 <= io_in;
      if (_GEN_0 & io_select == 5'h14)
        regs_20 <= io_in;
      if (_GEN_0 & io_select == 5'h15)
        regs_21 <= io_in;
      if (_GEN_0 & io_select == 5'h16)
        regs_22 <= io_in;
      if (_GEN_0 & io_select == 5'h17)
        regs_23 <= io_in;
      if (_GEN_0 & io_select == 5'h18)
        regs_24 <= io_in;
      if (_GEN_0 & io_select == 5'h19)
        regs_25 <= io_in;
      if (_GEN_0 & io_select == 5'h1A)
        regs_26 <= io_in;
      if (_GEN_0 & io_select == 5'h1B)
        regs_27 <= io_in;
      if (_GEN_0 & io_select == 5'h1C)
        regs_28 <= io_in;
      if (_GEN_0 & io_select == 5'h1D)
        regs_29 <= io_in;
      if (_GEN_0 & io_select == 5'h1E)
        regs_30 <= io_in;
      if (_GEN_0 & (&io_select))
        regs_31 <= io_in;
    end
  end // always @(posedge)
  assign io_out = _GEN[io_select];
endmodule

