// Generated by CIRCT firtool-1.128.0
module VGAController(
  input         clock,
                reset,
  output        io_hsync,
                io_vsync,
  output [11:0] io_rgb,
  output        io_blanking,
  output [9:0]  io_hPos,
                io_vPos
);

  reg  [9:0] hCount;
  reg  [9:0] vCount;
  wire       active = hCount < 10'h280 & vCount < 10'h1E0;
  always @(posedge clock) begin
    if (reset) begin
      hCount <= 10'h0;
      vCount <= 10'h0;
    end
    else begin
      automatic logic _GEN = hCount == 10'h31F;
      hCount <= _GEN ? 10'h0 : hCount + 10'h1;
      if (_GEN)
        vCount <= vCount == 10'h20C ? 10'h0 : vCount + 10'h1;
    end
  end // always @(posedge)
  assign io_hsync = ~(hCount > 10'h28F & hCount < 10'h2F0);
  assign io_vsync = ~(vCount > 10'h1E9 & vCount < 10'h1EC);
  assign io_rgb = {12{active}};
  assign io_blanking = ~active;
  assign io_hPos = hCount;
  assign io_vPos = vCount;
endmodule

